### ISSUE TITLE
std::nothrow was not passed to operator new or no try {} catch

### ISSUE THREAD

**Issue by deemetrius** [Anonymus-Player/HackySTL#39]
https://github.com/HackyTeam/HackySTL/blob/e881f80ec085b6ba4e6dabb4c20be58bde00c0f1/lib/Allocator.hpp#L422

Seems that you just can't compare _result to nullptr.

Sorry if I'm wrong.

**Comment by Unicode-Hater** [comment]
The tests are built using `-fno-except` using [this](https://github.com/HackyTeam/HackySTL/blob/dev/Debuggers/Linux/tasks.json) json configuration. I don't really know if it calls the `nothrow` overload of it, but I can ask someone smarter than me who's working with me. What do you say @dekrain

**Comment by deemetrius** [comment]
So does this library is not designed for users who use exceptions in their code?

**Comment by Unicode-Hater** [comment]
> So does this library is not designed for users who use exceptions in their code?

I haven't put any thought into that matter, because I have really strong opinions on exceptions, plus there is `Result` which aims to replace them, also if the class name sounds familiar is because it was inspired by the same "feature" Rust has [link](https://doc.rust-lang.org/std/result/). Feel free to argue in contrary

**Comment by deemetrius** [comment]
> Feel free to argue in contrary

In one project I have some base function that call other function that call another function, etc. such chains.
So I have to use exceptions to "jump-out" from target function to base function directly.
Without exceptions I supposed to write code that checks return values in **each element** of that chain.

So exceptions are good in some cases (and code bloat is not desired).

Moreother: In my case I can throw one type of exception or another to jump-out with different state and catch separately. Or even catch in other position in the chain.
Without exceptions this leads me to use std::variant-like class as Result, that I not wish to use in this case.

**Comment by Unicode-Hater** [comment]
Regarding exceptions support, I won't implement it, because I don't agree with them and personally think what you are doing there is not really great, because you are using an ABI feature as a control flow, which is one of the unintended functionalities. As for the original issue it's now fixed by [7b6608b](https://github.com/HackyTeam/HackySTL/commit/7b6608bca169fc9c0bb7a51e08d73491a1a11ab8)
